name: flutter_training
description: "A new Flutter learning project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4
  flutter: ^3.24.5

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16
  yumemi_weather:
    git:
      url: https://github.com/yumemi-inc/flutter-training-template.git
      ref: main
      path: packages/yumemi_weather

dev_dependencies:
  flutter_test:
    sdk: flutter
  yumemi_lints: ^2.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
